#!/usr/bin/env node
/**
 * Builds an icon subset — the only icons your site actually uses.
 *
 *   node scripts/build-icons.mjs                 # the default set, into the repo
 *   node scripts/build-icons.mjs mic chat mail   # just those three, to ./icons/
 *
 * Why a generator rather than a pack. Lucide is 1,767 icons and 476 KB. Vendoring
 * it whole would make the icon layer thirty times the size of the stylesheet it
 * decorates, and a <use href="sprite.svg#mic"> downloads the entire file to draw
 * one glyph. So the full sprite lives in vendor/ and never reaches a browser;
 * what ships is whatever you name here.
 *
 * Emits two things, because there are two honest ways to use an icon:
 *
 *   icons.svg   a subset sprite. One request, cached, no JS:
 *               <svg class="icon"><use href="icons.svg#fw-mic"/></svg>
 *
 *   icons.css   the same icons as mask-image data URIs. No extra request and
 *               no path to resolve relative to the stylesheet, which is what
 *               breaks a sprite when the CSS is served from elsewhere:
 *               <i class="icon i-mic"></i>
 *
 * Both take their colour from currentColor, so light and dark need no second set.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** The theme's own components need these; everything else is opt-in. */
const DEFAULT_SET = [
  // channels
  "mic", "keyboard", "message-square", "phone", "mail", "mailbox", "globe",
  // shell
  "menu", "x", "check", "chevron-down", "search", "external-link", "circle-alert",
];

/** Friendlier names for the theme's vocabulary, mapped onto Lucide's. */
const ALIASES = {
  chat: "message-square",
  post: "mailbox",
  close: "x",
  alert: "circle-alert",
  external: "external-link",
};

/** Lucide has no brand marks — removed deliberately, over trademark. These
 *  come from Tabler (MIT) and are the only artwork not from Lucide. */
const BRANDS = { whatsapp: "brand-whatsapp", telegram: "brand-telegram" };

const STROKE = 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

function lucideBody(name) {
  const sprite = readFileSync(join(root, "vendor/lucide/sprite.svg"), "utf8");
  const m = sprite.match(new RegExp(`<symbol id="${name}"[^>]*>([\\s\\S]*?)</symbol>`));
  if (!m) throw new Error(`no such Lucide icon: "${name}" — check https://lucide.dev/icons`);
  return m[1].trim();
}

function tablerBody(file) {
  const svg = readFileSync(join(root, `vendor/tabler/${file}.svg`), "utf8");
  const inner = svg.replace(/[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>[\s\S]*/, "");
  // Tabler ships a transparent bounding path first; it is not artwork.
  return inner.replace(/<path stroke="none"[^/]*\/>/g, "").trim();
}

/** Resolve a requested name to its artwork and the licence that covers it. */
function resolve(name) {
  if (name in BRANDS) return { body: tablerBody(BRANDS[name]), source: "Tabler (MIT)" };
  const lucideName = ALIASES[name] ?? name;
  return { body: lucideBody(lucideName), source: "Lucide (ISC)" };
}

function buildSprite(icons) {
  const symbols = icons
    .map(({ name, body }) => `  <symbol id="fw-${name}" viewBox="0 0 24 24">\n    ${body.replace(/\n\s*/g, "\n    ")}\n  </symbol>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  flywheel-theme icons — generated by scripts/build-icons.mjs. Do not edit.

  Artwork: Lucide (ISC, © Lucide Icons and Contributors) except the brand
  marks, which are Tabler (MIT, © Paweł Kuna). Full licences in vendor/.

  Telegram and WhatsApp are trademarks. They are here to label a link to
  those services, which is ordinary nominative use.
-->
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <defs><style>
    symbol { fill: none; stroke: currentColor; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }
  </style></defs>
${symbols}
</svg>
`;
}

function buildCss(icons) {
  const rules = icons
    .map(({ name, body }) => {
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" ${STROKE.replace("currentColor", "%23000")}>${body.replace(/\s+/g, " ")}</svg>`;
      // Only what a URL actually cannot carry; over-encoding doubles the size.
      const uri = svg.replace(/"/g, "'").replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23");
      return `.i-${name} { --fw-i: url("data:image/svg+xml,${uri}"); }`;
    })
    .join("\n");

  return `/* flywheel-theme icons — generated by scripts/build-icons.mjs. Do not edit.
 *
 * Artwork: Lucide (ISC) except the brand marks, which are Tabler (MIT).
 * Full licences in vendor/.
 *
 *   <link rel="stylesheet" href="icons.css">
 *   <i class="icon i-mic"></i>
 *
 * The glyph is a mask, so it is painted in currentColor and inherits whatever
 * the surrounding text is — one set for light and dark.
 */
.icon {
  display: inline-block;
  width: 1.25em; height: 1.25em;
  vertical-align: -0.2em;
  flex: none;                    /* never squashed by a flex parent */
}
/* <svg class="icon"><use .../></svg> takes its colour from the stroke;
 * <i class="icon i-*"></i> is a mask painted in the current colour. */
i.icon {
  background-color: currentColor;
  -webkit-mask: var(--fw-i) center / contain no-repeat;
          mask: var(--fw-i) center / contain no-repeat;
}

${rules}
`;
}

const requested = process.argv.slice(2);
const names = requested.length ? requested : [...DEFAULT_SET.map((n) => Object.keys(ALIASES).find((a) => ALIASES[a] === n) ?? n), ...Object.keys(BRANDS)];

let icons;
try {
  icons = names.map((name) => ({ name, ...resolve(name) }));
} catch (e) {
  // A typo should read like a sentence, not a stack trace.
  console.error(`build-icons: ${e.message}`);
  process.exit(1);
}

const outDir = requested.length ? join(root, "icons") : root;
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

const sprite = buildSprite(icons);
const css = buildCss(icons);
writeFileSync(join(outDir, "icons.svg"), sprite);
writeFileSync(join(outDir, "icons.css"), css);

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} KB`;
console.log(`${icons.length} icons → ${outDir.replace(root, ".") || "."}`);
console.log(`  icons.svg  ${kb(sprite)}`);
console.log(`  icons.css  ${kb(css)}`);
const byBrand = icons.filter((i) => i.source.startsWith("Tabler")).map((i) => i.name);
if (byBrand.length) console.log(`  from Tabler (MIT): ${byBrand.join(", ")}; the rest from Lucide (ISC)`);
